In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
A = np.array([[0,1],[-2,-3]])
print(A)

[[ 0  1]
 [-2 -3]]


In [5]:

w,v = np.linalg.eig(A)
print('E-value:', w)
print('E-vector', v)

E-value: [-1. -2.]
E-vector [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [7]:
#Problem Begins Part 1:Defining Matrix

B = np.array([[11,-1,0],[-1,12,-1],[0,-1,11]])
print(B)


[[11 -1  0]
 [-1 12 -1]
 [ 0 -1 11]]


In [8]:
#Part 2: finding eigenvaules and eigenvectors

w,v = np.linalg.eig(B)
print('E-value:', w)
print('E-vector', v)

E-value: [13. 11. 10.]
E-vector [[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  1.03471073e-15  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
