In [29]:
import numpy as np
%matplotlib inline


In [30]:
#P0

A = np.array([ [2,4,-7],[3,-3,0],[1,7,5] ])
B = np.array([ [2,4],[-3,3],[1,7] ])
C = np.array([ [-1,1],[1,-1]])
D = np.array([ [2,0],[-3,6]])

print("A:\n",A)
print("A:\n",B)
print("A:\n",C)
print("A:\n",D)

A:
 [[ 2  4 -7]
 [ 3 -3  0]
 [ 1  7  5]]
A:
 [[ 2  4]
 [-3  3]
 [ 1  7]]
A:
 [[-1  1]
 [ 1 -1]]
A:
 [[ 2  0]
 [-3  6]]


In [31]:
#P1
c = 2.5
CA = c*A
print("CA:\n",CA)

CA:
 [[  5.   10.  -17.5]
 [  7.5  -7.5   0. ]
 [  2.5  17.5  12.5]]


In [32]:
#P2
#CA = np.matmul(C,A)
#print("CA = \n",CA)
CD = np.matmul(C,D)
print("CD = \n",CD)
DC = np.matmul(D,C)
print("DC = \n",DC)



CD = 
 [[-5  6]
 [ 5 -6]]
DC = 
 [[-2  2]
 [ 9 -9]]


In [33]:
#P3
B_T = B.T
print("B_T:\n",B_T)

B_T:
 [[ 2 -3  1]
 [ 4  3  7]]


In [34]:
#P4
CD_add = C + D
print("\nC+D:\n",CD_add)


C+D:
 [[ 1  1]
 [-2  5]]


In [35]:
#P5
detC = np.linalg.det(C)
print(detC)

0.0


In [36]:
#P6
detA = np.linalg.det(A)
print(detA)

-257.9999999999998
